### ISSUE TITLE
Change the alert box to modal box.

### ISSUE THREAD

**Issue by monojkhatua** [spotphish/spotphish#26]
Steps:
1. Add a site to whitelist.
2. Disable it from option page.
3. Try to add the same site through the popup menu.

![uploads/8a8dca97-3266-47b7-9db0-4c16cf9c8885/screenshot_Wed_Jul_19_16.04.28.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8a8dca97-3266-47b7-9db0-4c16cf9c8885%2Fscreenshot_Wed_Jul_19_16.04.28.png)

**Comment by anil5356** [comment]
commit 352ff0abbde491b65bf66ba2e06decd7313bdcfa
Author: Anil Khuteta <anil.khuteta@gmail.com>
Date:   Thu Jul 20 11:10:44 2017 +0530

    bugfix: disbaled whitelist items handled in popup
