### ISSUE TITLE
Report Phishing and Report False Alarm features are not working.

### ISSUE THREAD

**Issue by monojkhatua** [spotphish/spotphish#31]
The Report Phishing and Report False Alarm features are not functional now. When we click on this two buttons the UI moves nowhere. At least we should close the popup  on clicking the above two buttons.

Other suggestion is to disable/hide these buttons for the current release.

**Comment by anil5356** [comment]
For now, let's change the "Report false positive" button to "add to skiplist". This will ensure that users have a way to stop false positives.
