### ISSUE TITLE
Security image shown after login is successful

### ISSUE THREAD

**Issue by kousik97** [spotphish/spotphish#37]
While logging into facebook, the security image is shown after the login is successful and at every time when the home page is reloaded. Once the password is given, there is no need for the security image to be shown. I do not know whether it is a feature that you would like to have or an error. Please elaborate more on this.

**Comment by ganeshv** [comment]
This is a known issue.

The problem with Facebook (and reddit and others) is that the same URL is used for the login dialog as well as for displaying content. We haven't yet found a robust way of distinguishing between login/non-login cases which works across sites. Worst case we have to bite the bullet and make a site-specific check.
