### ISSUE TITLE
Issues related to Security Image Page

### ISSUE THREAD

**Issue by skatkojwar** [spotphish/spotphish#41]
1. The Uploaded image should be deleted only when another image is uploaded. It should retain newly uploaded image, follow steps to reproduce:
	- Upload an image, it will be set as a security image
	- Set another image image from defaults
	- Now try to set uploaded image as a security image, you can't.
2. When restart the chrome browser, none of the default images is marked as favorite
3. When a new security image is uploaded, earlier selected image from defaults and newly uploaded image both marked as favorite
4. Correct an error message, actual message "The image size (size) should not be (n)ore than 2MB", should be "The image size should not be more than 2MB". Find diff in brackets.

**Comment by deepakshinde** [comment]
Fixed on "ds-change-monoj" branch

**Comment by skatkojwar** [comment]
RESTORE does not delete personal security image / restore default security image. It used to work earlier.

**Comment by deepakshinde** [comment]
Fixed. When you click on the RESTORE button  personal security image will be deleted.

**Comment by skatkojwar** [comment]
Recent pull does not seem to have this change. Please verify once.
Please handle below issues along with the one above:
- User can select an empty image on clicking UPLOAD IMAGE container
- User is not able to select an uploaded image by clicking on favorite icon

**Comment by skatkojwar** [comment]
Verified and working fine now.
