### ISSUE TITLE
Few URLs under amazon not getting deleted

### ISSUE THREAD

**Issue by anil5356** [spotphish/spotphish#42]
6 URLs under amazon.com are not getting deleted or enabled/disabled. Null exception is raised on trying. Attached is a snapshot.

![uploads/e2d608a6-4aab-4342-9e18-a6e088924948/Screen Shot 2017-10-10 at 12.45.57 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe2d608a6-4aab-4342-9e18-a6e088924948%2FScreen+Shot+2017-10-10+at+12.45.57+PM.png)

**Comment by monojkhatua** [comment]
It is a config issue. updated the config file.
