### ISSUE TITLE
Unprotected site retains in Safe Doamins

### ISSUE THREAD

**Issue by skatkojwar** [spotphish/spotphish#50]
Steps to reproduce:
- Protect SBI login page
- 'retail.onlinesbi.com' gets added to safe domains list
- Unprotect the site
- Navigate to Safe Domains page and delete SBI domain manually, gets deleted
- Reload options page, SBI domain retains in safe domains list

**Comment by monojkhatua** [comment]
This issue is outdated. The workflow has changed now.
