### ISSUE TITLE
Custom site gets deleted on deletion of one of the protected urls

### ISSUE THREAD

**Issue by skatkojwar** [spotphish/spotphish#51]
If we delete one of the pages from custom protected sites, whole site is getting deleted.
Steps to reproduce:
- Protect a SBI login page "https://retail.onlinesbi.com/retail/login.htm"
- Protect "https://retail.onlinesbi.com/nretail/login.htm" and "https://retail.onlinesbi.com/mretail/login.htm", these gets added to custom site of Onlinesbi.
- Delete any of the urls and whole site gets deleted.

**Comment by monojkhatua** [comment]
Fixed in dev branch

**Comment by skatkojwar** [comment]
Verified. Works well.
