### ISSUE TITLE
Default protected site allows only one url to get deleted

### ISSUE THREAD

**Issue by skatkojwar** [spotphish/spotphish#52]
In default protected site if we delete more than 2 pages, it deletes only the last one selected for deletion.
Steps to reproduce:
- Navigate to SpotPhish Settings > Protected Pages
- From Facebook site, delete "https://www.facebook.com/login/" and then "https://www.facebook.com/reg/"
- Refresh the page and see only "https://www.facebook.com/reg/" gets deleted and other one retains
- Later if we delete "https://www.facebook.com/login/",  gets deleted and "https://www.facebook.com/reg/" comes back

**Comment by monojkhatua** [comment]
Fixed in dev branch

**Comment by skatkojwar** [comment]
Working fine.
