### ISSUE TITLE
Upload backup file shows error "Please upload a valid format file."

### ISSUE THREAD

**Issue by skatkojwar** [spotphish/spotphish#59]
Steps to reproduce:
- Navigate to Settings > Advanced
- Click Backup, to download a backup file
- Click Upload File to restore
- Select downloaded backup file(json format)
- It throws error showing "Please upload a valid format file."

Chrome Version 59.0.3071.86
Backup file format: JSON

**Comment by deepakshinde** [comment]
I have added fix for this validation error.
